# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(editable=False, help_text="The user's primary login handle from the authentication service.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The first time the user had any activity in the system')),
            ],
        ),
    ]
